### ISSUE TITLE
FFI not working on ECL

### ISSUE THREAD

**Issue by mmontone** [rpav/cl-cairo2#24]
The FFI for creating a Cairo surface doesn't work from ECL (Embedded Common Lisp)

```
(cairo::cairo_image_surface_create (cairo::lookup-enum :argb32 cairo::table-format)
                              100 100)
```

=>

```
#<foreign :POINTER-VOID>
```

I cannot figure out why, as the FFI code is very straightforward:

```
(cffi:defcfun ("cairo_image_surface_create" cairo_image_surface_create) :pointer
  (format cairo_format_t)
  (width :int)
  (height :int))
```

**Comment by dkochmanski** [comment]
This is not the issue you face. `#<foreign :pointer-void>` doesn't mean NULL pointer, just void pointer (C type `(void *)`). Since it seems to cause confusion, I've added a ticket here:

https://gitlab.com/embeddable-common-lisp/ecl/issues/440

Try calling: `(ffi:null-pointer-p *your-pointer*)` to see yourself. This ticket should be closed as invalid.

That doesn't mean that `cl-cairo2` works on ECL, I don't know if it does. It just means that this description does not indicate a problem (I've tried it and this function indeed returns a pointer, which is not NULL).
